In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/PRAJJWALmehta/Machine-Learning-/main/Data/USA_Housing.csv')
df.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0       79545.45857             5.682861                   7.009188   
1       79248.64245             6.002900                   6.730821   
2       61287.06718             5.865890                   8.512727   
3       63345.24005             7.188236                   5.586729   
4       59982.19723             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  
0                          4.09      23086.80050  1.059034e+06  
1                          3.09      40173.07217  1.505891e+06  
2                          5.13      36882.15940  1.058988e+06  
3                          3.26      34310.24283  1.260617e+06  
4                          4.23      26354.10947  6.309435e+05

In [ ]:
X=df.iloc[:,:5]
Y=df.iloc[:,5]
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled= np.insert(X_scaled, 0, values=1, axis=1)

In [ ]:
accuracy = 0

# Cross Validation- Fold 1

In [ ]:
import numpy as np
X_train=X_scaled[:4000,:]
X_test=X_scaled[4000:5000,:]
Y_train=Y[:4000]
Y_test=Y[4000:5000]
Y_train=(np.array(Y_train)).reshape(-1,1)
Y_test=(np.array(Y_test)).reshape(-1,1)

### Finding the Beta Matrix

In [ ]:
import numpy as np
A=X_train.T.dot(X_train)
B=np.linalg.inv(A)
C=B.dot(X_train.T)
D1=C.dot(Y_train)
print(D1)

[[1233028.38536436]
 [ 230778.59921985]
 [ 163755.13607252]
 [ 121885.1351222 ]
 [   1247.01304382]
 [ 150084.29759618]]


In [ ]:
y_predict=X_test.dot(D1)
print(y_predict)

[[1457655.14509262]
 [1298104.16714785]
 [1650238.22147915]
 [1605071.83890936]
 [1404788.08286058]
 [1543416.35563577]
 [1364105.23837493]
 [1464953.62802342]
 [1094094.64619444]
 [1158087.94530995]
 [1511152.56199184]
 [1046492.34578515]
 [1146556.39584728]
 [1259132.86913504]
 [ 951852.22073643]
 [1336707.0374408 ]
 [1625733.18779646]
 [1292949.70767621]
 [1331550.41492348]
 [1741540.8736312 ]
 [1169156.93563025]
 [1635074.26335467]
 [1413875.04178438]
 [1262012.73379097]
 [1385644.43638768]
 [ 859121.05235639]
 [ 798820.59132736]
 [ 915218.74460299]
 [ 942636.20977044]
 [1506585.09649504]
 [1848833.64327817]
 [1244268.717695  ]
 [1592507.19031079]
 [ 887720.74173755]
 [ 504984.73986602]
 [ 657861.75613857]
 [1422024.01677379]
 [1533974.6363799 ]
 [1188949.94231217]
 [1657671.33609735]
 [ 839103.44475237]
 [1078152.94258651]
 [1161935.02701188]
 [1145551.70447918]
 [1160261.74446638]
 [1251304.61747991]
 [1194844.85231176]
 [ 967996.37835262]
 [1126122.20316288]
 [1329182.47617701]


### mean square error and accuracy

In [ ]:
error=Y_test-y_predict
print(error.shape)
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
print(sum_square_error/len(y_predict))
y_mean=np.mean(Y_test)
total_variance=np.sum((Y_test-y_mean)**2)
accuracy += 1-sum_square_error/total_variance
print(1-sum_square_error/total_variance)

(1000, 1)
10415367206.826326
0.9138111758717495


# Cross Validation Fold -2

In [ ]:
import numpy as np
X_train1=X_scaled[:3000,:]
X_train2=X_scaled[4000:5000,:]
X_train=np.append(X_train1,X_train2,axis=0)
X_test=X_scaled[3000:4000,:]
Y_train1=Y[:3000]
Y_train2=Y[4000:]
Y_train=np.append(Y_train1,Y_train2,axis=0)
Y_test=Y[3000:4000]
Y_train=(np.array(Y_train)).reshape(-1,1)
Y_test=(np.array(Y_test)).reshape(-1,1)

In [ ]:
import numpy as np
A=X_train.T.dot(X_train)
B=np.linalg.inv(A)
C=B.dot(X_train.T)
D2=C.dot(Y_train)
print(D2)

[[1.23144707e+06]
 [2.29921558e+05]
 [1.64523054e+05]
 [1.19737507e+05]
 [1.12425659e+03]
 [1.51317802e+05]]


In [ ]:
y_predict=X_test.dot(D2)
print(y_predict)

[[1448013.87496855]
 [1302297.98769045]
 [1356989.1983947 ]
 [1024678.57396309]
 [1433160.35841733]
 [ 689736.08918579]
 [1654085.16737835]
 [1750351.97438971]
 [1080163.83675324]
 [1378338.15831883]
 [ 574120.59522687]
 [1295805.16899164]
 [1614999.60263853]
 [1289275.18012125]
 [1024023.61189915]
 [1345757.24355485]
 [1501306.90320289]
 [1495057.97901345]
 [1152258.08515341]
 [1089619.76939195]
 [1309044.06588223]
 [1286412.24138619]
 [1814703.56541386]
 [2123082.02593582]
 [1393390.1097223 ]
 [ 875429.48642398]
 [1378263.63736203]
 [1626436.19836037]
 [1227749.37814889]
 [1365054.72687377]
 [1005596.51941615]
 [1290919.26647491]
 [1493230.48054068]
 [ 861157.99212629]
 [1831177.12550832]
 [1700511.22691728]
 [1299775.77572087]
 [ 834569.7684684 ]
 [ 948674.67498631]
 [1127732.62609894]
 [ 893673.15832414]
 [1199915.38123817]
 [1077643.71364022]
 [ 752591.71583495]
 [1090817.19147127]
 [1303733.32720858]
 [1253030.31627291]
 [1069522.43984815]
 [1321932.08243293]
 [ 920940.57103319]


In [ ]:
error=Y_test-y_predict
print(error.shape)
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
print(sum_square_error/len(y_predict))
y_mean=np.mean(Y_test)
total_variance=np.sum((Y_test-y_mean)**2)
accuracy += 1-sum_square_error/total_variance
print(1-sum_square_error/total_variance)

(1000, 1)
10176314743.926218
0.9208503836977656


# Cross Validation- Fold 3

In [ ]:
import numpy as np
X_train1=X_scaled[:2000,:]
X_train2=X_scaled[3000:5000,:]
X_train=np.append(X_train1,X_train2,axis=0)
X_test=X_scaled[2000:3000,:]
Y_train1=Y[:2000]
Y_train2=Y[3000:]
Y_train=np.append(Y_train1,Y_train2,axis=0)
Y_test=Y[2000:3000]
Y_train=(np.array(Y_train)).reshape(-1,1)
Y_test=(np.array(Y_test)).reshape(-1,1)

In [ ]:
import numpy as np
A=X_train.T.dot(X_train)
B=np.linalg.inv(A)
C=B.dot(X_train.T)
D3=C.dot(Y_train)
print(D3)

[[1231448.09063371]
 [ 230730.20810582]
 [ 163554.55706976]
 [ 121669.08713233]
 [   2620.25215054]
 [ 150923.12489298]]


In [ ]:
y_predict=X_test.dot(D3)
print(y_predict)

[[1231513.14886101]
 [1321188.78204718]
 [ 725691.26810135]
 [ 932558.61953863]
 [1049638.8423876 ]
 [1117792.169465  ]
 [ 699809.98998919]
 [1283202.33184976]
 [1449238.57178016]
 [1624951.44906872]
 [1830848.57926868]
 [1242649.34621863]
 [1210706.94443784]
 [ 896076.85897561]
 [1253715.05080186]
 [1589472.28056382]
 [ 928896.95960008]
 [ 250063.21203873]
 [1365038.62630567]
 [ 936630.15198787]
 [1463875.02234695]
 [ 749424.62715119]
 [1667477.50953431]
 [ 998159.02130739]
 [ 970325.82779316]
 [ 573081.70909738]
 [1541109.00744573]
 [1330273.78875683]
 [1187952.13853527]
 [2075817.91954476]
 [ 870316.85253847]
 [1457498.55657956]
 [1314368.18471005]
 [1590391.6033931 ]
 [1266820.62629774]
 [1066363.33746692]
 [1132272.9992175 ]
 [ 786556.52888475]
 [1126937.15042759]
 [1245724.72756982]
 [1768217.80885668]
 [ 671159.39117194]
 [1229061.2109537 ]
 [1399601.24562253]
 [1142854.62875621]
 [1220245.06194569]
 [1325950.85208369]
 [1658828.63278111]
 [ 927655.78891484]
 [ 665038.53594979]


In [ ]:
error=Y_test-y_predict
print(error.shape)
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
print(sum_square_error/len(y_predict))
y_mean=np.mean(Y_test)
total_variance=np.sum((Y_test-y_mean)**2)
accuracy += 1-sum_square_error/total_variance
print(1-sum_square_error/total_variance)

(1000, 1)
9861616305.461946
0.9152429915320014


# Cross validation Fold-4

In [ ]:
import numpy as np
X_train1=X_scaled[:1000,:]
X_train2=X_scaled[2000:,:]
X_train=np.append(X_train1,X_train2,axis=0)
X_test=X_scaled[1000:2000,:]
Y_train1=Y[:1000]
Y_train2=Y[2000:]
Y_train=np.append(Y_train1,Y_train2,axis=0)
Y_test=Y[1000:2000]
Y_train=(np.array(Y_train)).reshape(-1,1)
Y_test=(np.array(Y_test)).reshape(-1,1)

In [ ]:
import numpy as np
A=X_train.T.dot(X_train)
B=np.linalg.inv(A)
C=B.dot(X_train.T)
D4=C.dot(Y_train)
print(D4)

[[1232586.40453402]
 [ 228365.32287054]
 [ 165201.14881927]
 [ 122539.46855211]
 [   1697.03433458]
 [ 150055.81710562]]


In [ ]:
y_predict=X_test.dot(D4)
print(y_predict)

[[ 950080.82206093]
 [ 711724.26608798]
 [1770455.57819769]
 [ 764563.88271977]
 [1572061.16316271]
 [1317591.12280027]
 [1604930.7177251 ]
 [1759195.78943922]
 [1169222.38871881]
 [1431814.21935315]
 [1499538.56522023]
 [1341168.59871483]
 [1375149.91419856]
 [1405838.13193487]
 [1503218.88005213]
 [1848993.40521187]
 [1950500.92757011]
 [ 790658.38349116]
 [1190896.15599901]
 [1156468.95013955]
 [1267826.58554619]
 [1718149.71836485]
 [ 555011.64109618]
 [ 747482.33138753]
 [ 768207.63242427]
 [1124282.36925491]
 [1529826.94616795]
 [1754156.80533026]
 [1100222.13541817]
 [1329252.53932286]
 [1348093.65456371]
 [1486540.20018588]
 [1327911.08267484]
 [1436053.94607928]
 [1066299.26103231]
 [1353766.3907889 ]
 [1027101.14990834]
 [ 896561.25325758]
 [ 594610.41612626]
 [1491867.95632144]
 [ 908007.11467791]
 [1581286.7280654 ]
 [1665374.27725999]
 [1316450.51345274]
 [1367829.49347562]
 [1568361.59536923]
 [1361139.95705265]
 [1135124.72547678]
 [1004641.28638481]
 [1563938.32811944]


In [ ]:
error=Y_test-y_predict
print(error.shape)
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
print(sum_square_error/len(y_predict))
y_mean=np.mean(Y_test)
total_variance=np.sum((Y_test-y_mean)**2)
accuracy += 1-sum_square_error/total_variance
print(1-sum_square_error/total_variance)

(1000, 1)
10728109153.419218
0.920301549640113


# Cross Validation -Fold 5

In [ ]:
import numpy as np
X_train=X_scaled[1000:,:]
X_test=X_scaled[:1000,:]
Y_train=Y[1000:]
Y_test=Y[:1000]
Y_train=(np.array(Y_train)).reshape(-1,1)
Y_test=(np.array(Y_test)).reshape(-1,1)

In [ ]:
import numpy as np
A=X_train.T.dot(X_train)
B=np.linalg.inv(A)
C=B.dot(X_train.T)
D5=C.dot(Y_train)
print(D5)

[[1231872.07704612]
 [ 229923.70318635]
 [ 164052.98579011]
 [ 120923.57426579]
 [   3533.77470973]
 [ 151855.58542488]]


In [ ]:
y_predict=X_test.dot(D5)
print(y_predict)

[[1222472.59789716]
 [1494131.15197358]
 [1253670.80242078]
 [1120389.19877662]
 [ 844315.19005474]
 [1068260.55667213]
 [1671245.639246  ]
 [1567875.18249614]
 [ 763347.28814599]
 [1470721.64690957]
 [1775501.83443543]
 [ 630026.09214137]
 [ 950539.75749648]
 [1303433.26478986]
 [1306505.35508872]
 [1237586.54456661]
 [1521433.87536906]
 [ 488187.16489613]
 [1137920.58807016]
 [1203167.64046499]
 [2019384.21819711]
 [1076240.13702178]
 [ 734801.62065626]
 [ 997288.25431527]
 [ 900094.94841917]
 [1473156.57255351]
 [1237124.03621889]
 [ 930137.78874904]
 [1405712.96683316]
 [1373314.62542769]
 [1246117.10168385]
 [1224015.69281346]
 [1234384.89038389]
 [ 611159.97921256]
 [ 937440.62317097]
 [1274345.51392185]
 [1330861.45766804]
 [1161935.74224449]
 [ 525180.40929258]
 [  97206.19765112]
 [ 929627.49901683]
 [1714160.39150958]
 [ 792704.11688002]
 [1611877.74359594]
 [ 943225.3232602 ]
 [1443933.98877536]
 [1222266.83903772]
 [1070537.83047054]
 [1228326.71172751]
 [1744277.04002954]


In [ ]:
error=Y_test-y_predict
print(error.shape)
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
print(sum_square_error/len(y_predict))
y_mean=np.mean(Y_test)
total_variance=np.sum((Y_test-y_mean)**2)
accuracy += 1-sum_square_error/total_variance
print(1-sum_square_error/total_variance)

(1000, 1)
10087104444.118813
0.9175899480765107


# Average Accuracy on Training Data 

In [ ]:
print(accuracy/5)

0.9175592097636281


# Model Evaluation 

for Model Evaluation we train with 70% data and test with the remaining 30%

In [ ]:
import numpy as np
X_train=X_scaled[:3500,:]
X_test=X_scaled[3500:5000,:]
Y_train=Y[:3500]
Y_test=Y[3500:5000]
Y_train=(np.array(Y_train)).reshape(-1,1)
Y_test=(np.array(Y_test)).reshape(-1,1)

In [ ]:
y_predict=X_test.dot(D2)
print(y_predict)

[[ 854827.76479024]
 [1281641.86868854]
 [2013490.16147134]
 ...
 [1025021.77734944]
 [1262205.87983883]
 [1302088.08443965]]


In [ ]:
error=Y_test-y_predict
print(error.shape)
square_error=np.power(error,2)
sum_square_error=np.sum(square_error)
print(sum_square_error/len(y_predict))
y_mean=np.mean(Y_test)
total_variance=np.sum((Y_test-y_mean)**2)
print(1-sum_square_error/total_variance)

(1500, 1)
10176167895.509493
0.917786034446557
