In [26]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [27]:
df=pd.read_csv('https://raw.githubusercontent.com/PRAJJWALmehta/Machine-Learning-/main/Data/USA_Housing.csv')
df.describe()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
count       5000.000000          5000.000000                5000.000000   
mean       68583.108984             5.977222                   6.987792   
std        10657.991214             0.991456                   1.005833   
min        17796.631190             2.644304                   3.236194   
25%        61480.562390             5.322283                   6.299250   
50%        68804.286405             5.970429                   7.002902   
75%        75783.338665             6.650808                   7.665871   
max       107701.748400             9.519088                  10.759588   

       Avg. Area Number of Bedrooms  Area Population         Price  
count                   5000.000000      5000.000000  5.000000e+03  
mean                       3.981330     36163.516039  1.232073e+06  
std                        1.234137      9925.650114  3.531176e+05  
min                        2.000000       172.610686  1.593866e+04  
25%                        3.140000     29403.928700  9.975771e+05  
50%                        4.050000     36199.406690  1.232669e+06  
75%                        4.490000     42861.290770  1.471210e+06  
max                        6.500000     69621.713380  2.469066e+06

In [34]:
import numpy as np
X=df.iloc[:,0:5]
Y=df.iloc[:,5]
Y=np.array(Y)
Y=Y.reshape(-1,1)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)


In [35]:
from sklearn.model_selection import train_test_split
X_intermediate, X_test, Y_intermediate, Y_test = train_test_split(X_scaled, Y, test_size=0.3, random_state=42)
X_train, X_validation, Y_train, Y_validation = train_test_split(X_intermediate,Y_intermediate,test_size=0.2,random_state=42)
print(Y_validation.shape)

(700, 1)


In [36]:
beta=np.zeros((6,4))
number_of_iterations=100
learning_rate=[0.001,0.01,0.1,1]
n=len(df)
for k in range(len(learning_rate)):
    for i in range(number_of_iterations):
        x0_gradient=0
        x1_gradient=0
        x2_gradient=0
        x3_gradient=0
        x4_gradient=0
        x5_gradient=0    
        for j in range(len(X_train)):
            a=X_train[j,0]
            b=X_train[j,1]
            c=X_train[j,2]
            d=X_train[j,3]
            e=X_train[j,4]
            f=Y_train[j]
            x0_gradient+=(beta[0][k]+(beta[1][k]*a)+(beta[2][k]*b)+(beta[3][k]*c)+(beta[4][k]*d)+(beta[5][k]*e)-f)
            x1_gradient+=((beta[0][k]+(beta[1][k]*a)+(beta[2][k]*b)+(beta[3][k]*c)+(beta[4][k]*d)+(beta[5][k]*e)-f)*a)
            x2_gradient+=((beta[0][k]+(beta[1][k]*a)+(beta[2][k]*b)+(beta[3][k]*c)+(beta[4][k]*d)+(beta[5][k]*e)-f)*b)
            x3_gradient+=((beta[0][k]+(beta[1][k]*a)+(beta[2][k]*b)+(beta[3][k]*c)+(beta[4][k]*d)+(beta[5][k]*e)-f)*c)
            x4_gradient+=((beta[0][k]+(beta[1][k]*a)+(beta[2][k]*b)+(beta[3][k]*c)+(beta[4][k]*d)+(beta[5][k]*e)-f)*d)
            x5_gradient+=((beta[0][k]+(beta[1][k]*a)+(beta[2][k]*b)+(beta[3][k]*c)+(beta[4][k]*d)+(beta[5][k]*e)-f)*e)
        beta[0][k]=beta[0][k]-((learning_rate[k]/n)*x0_gradient)
        beta[1][k]=beta[1][k]-((learning_rate[k]/n)*x1_gradient)
        beta[2][k]=beta[2][k]-((learning_rate[k]/n)*x2_gradient)
        beta[3][k]=beta[3][k]-((learning_rate[k]/n)*x3_gradient)
        beta[4][k]=beta[4][k]-((learning_rate[k]/n)*x4_gradient)
        beta[5][k]=beta[5][k]-((learning_rate[k]/n)*x5_gradient)
print(beta)
       
        

[[  67133.53630358  529329.43227428 1228654.4243101  1232618.32011841]
 [  12589.61696567   99003.272281    229235.11954318  230067.9889464 ]
 [   8683.53334913   68841.91685442  162993.67784305  163710.33259401]
 [   8194.33276617   58621.16538896  118985.55459136  121681.42752284]
 [   4810.52859515   28672.72378661    5954.61215367    2832.15066521]
 [   7239.00498571   59053.06185437  149987.90210255  150657.52262836]]


In [37]:
beta=pd.DataFrame(data=beta)
print(beta[0])

0    67133.536304
1    12589.616966
2     8683.533349
3     8194.332766
4     4810.528595
5     7239.004986
Name: 0, dtype: float64


In [38]:
X_validation=np.insert(X_validation,0,values=1,axis=1)
X_test=np.insert(X_test,0,values=1,axis=1)

In [39]:
import sklearn
from sklearn import metrics
for i in range(len(learning_rate)):
    validation_error=metrics.r2_score(Y_validation,X_validation.dot(beta[i]))    
    test_error=metrics.r2_score(Y_test,X_test.dot(beta[i]))
    print(validation_error,test_error)

-10.499535644463432 -11.570154129396213
-3.2391364999526324 -3.639254194674658
0.910087841876989 0.9143255087986946
0.9097995626742028 0.9147570103083724
